[roborpc.robot_env]
env_update_rate = 10
use_controller = false

######### Robot Environment Configuration #########
# This section defines the environment configuration for the robots.
[roborpc.robots]
# ON or OFF
robot_ids = [['panda_1']]
server_ips_address = ['127.0.0.1']
sever_rpc_ports = ['4098']

[roborpc.robots.realman]
[roborpc.robots.realman.realman_1]
ip_address = '192.168.1.18'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.realman.realman_2]
ip_address = '192.168.1.19'
robot_arm_dof = 6
robot_gripper_dof = 1

[roborpc.robots.realman.realman_3]
ip_address = '192.168.1.20'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.realman.realman_4]
ip_address = '192.168.1.21'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.franka.panda_1]
ip_address = '192.168.1.20'
robot_arm_dof = 7
robot_gripper_dof = 1
start_arm_joints = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0]
start_gripper_joints = [0.0]

[roborpc.robots.franka.panda_2]
ip_address = '192.168.1.21'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.isaac_sim.isaac_sim_single_franka]
ip_address = '127.0.0.1'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.dynamixel.dynamixel_controller_panda_1]
start_joints = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0] # panda: [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0], realman: [0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0]
joint_ids = [0, 1, 2, 3, 4, 5, 6]
joint_signs = [1, -1, 1, -1, 1, 1, 1]
gripper = true
port = "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5837053188-if00"
joint_offsets =  [3.141592653589793, 3.141592653589793, 6.283185307179586, 1.5707963267948966, 0.0, 6.283185307179586, 6.283185307179586]
gripper_config = [7, 350, 308]
baudrate = 1000000

[roborpc.robots.dynamixel.dynamixel_controller_realman_1]
start_joints = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0] # panda: [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0], realman: [0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0]
joint_ids = [0, 1, 2, 3, 4, 5, 6]
joint_signs = [1, -1, 1, -1, 1, 1, 1]
gripper = true
port = "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5837053188-if00"
joint_offsets =  [3.141592653589793, 3.141592653589793, 6.283185307179586, 1.5707963267948966, 0.0, 6.283185307179586, 6.283185307179586]
gripper_config = [7, 350, 308]
baudrate = 1000000

######### Camera Configuration #########
# This section defines the camera configuration for the robots.
[roborpc.cameras]
# ON or OFF
camera_ids = [['camera_1', 'camera_2', 'camera_3']]
server_ips_address = ['127.0.0.1']
server_rpc_ports = ['4098']

[roborpc.cameras.realsense_camera.realsense_camera_1]
camera_resolution = [640, 480]
camera_fps = 30
camera_serial_number = '231122070394'

[roborpc.cameras.realsense_camera.realsense_camera_2]
camera_resolution = [640, 480]
camera_fps = 30
camera_serial_number = '218622275485'

######### Controller Configuration #########
# This section defines the controller configuration for the robots.
[roborpc.controllers]
# ON or OFF
controller_ids = [['dynamixel_controller_panda_1']]
control_robot_ids = [['panda_1']]
server_ips_address = ['127.0.0.1']
sever_rpc_ports = ['']

######### Data Collector Configuration #########
# This section defines the data collector configuration for the robots.
[roborpc.collector.data_collector]
save_data_dir = "/media/jz08/SSD1/Log/droid/data/"
action_space = "joint_position"
gripper_action_space = "gripper_position"
use_one_side_camera = false # olny record left camera
use_hand_camera = true
use_left_camera = true
use_right_camera = true
use_rgb = true
use_depth = true
use_pointcloud = false
concatenate_images = false
image_width = 1280 #480
image_height = 720 #270
save_data_mode = "H5_FULL" # H5_SVO or H5_FULL or H5_MP4
save_data_speedup = false # for H5_SVO
use_zed_save_mp4 = false # for H5_MP4
save_audio = false
max_timesteps = 0 # 0 (not used) 1000
dt = 0.02 # act used
horizon = 300 # 0 for not used
use_align_color_depth = false
camera_fps = 15

######### Isaac Sim Robot Configuration #########
# This section defines the simulation robot configuration for the robots.
[roborpc.sim_robots.isaac_sim]
robot_ids = [['panda_1']]
camera_ids = [['camera_1', 'camera_2', 'camera_3']]
server_ips_address = ['127.0.0.1']
sever_rpc_ports = ['4098']
scene_usd_path = 'mustard_bottle.usd'
robot_usd_path = 'panda_fix_with_pull_bottle.usd'

[roborpc.sim_robots.isaac_sim.panda_1]
robot_arm_dof = 7
robot_gripper_dof = 2
action_dof = 9
robot_zero_action = [ -0.001229998898153242, -0.78373070703473, 0.00033452204524119444, -2.3621342130897784, -0.002939444554553038, 1.5585773693838316, 0.7862526640851296, 0.04,0.04 ]
gripper_raw_open_close_range = [0, 1]
gripper_normalized_open_close_range = [0.04, 0]
gripper_signs = [1, 1]
stiffnesses = [100000, 100000, 100000, 100000, 80000, 80000, 80000, 50000, 50000]
dampings = [8000, 8000, 8000, 8000, 5000, 5000, 5000, 2000, 2000]
base_word_pose = [0.0, 0.0, 0.0]

# for task
robot_description_path = 'panda_robot_descriptor.yaml'
rmpflow_config_path = 'panda_rmpflow_common.yaml'
urdf_path = 'franka_panda.urdf'
end_effector_frame_name = 'panda_link8'
gripper_base_link_prim_path = '/World/franka/panda_hand'
gripper_joint_prim_names = ["panda_finger_joint1", "panda_finger_joint2"]
arm_base_link_prim_path = '/World/franka/panda_link0'


[roborpc.sim_robots.isaac_sim.panda_2]
robot_arm_dof = 7
robot_gripper_dof = 2
action_dof = 15
robot_zero_action = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0, 0.0]
robot_description_path = 'panda_robot_descriptor.yaml'
rmpflow_config_path = 'panda_rmpflow_common.yaml'
urdf_path = 'franka_panda.urdf'
end_effector_frame_name = 'panda_link8'
gripper_base_link_prim_path = '/World/Robotiq_2F_85_edit/Robotiq_2F_85/base_link'
gripper_joint_prim_names = ["finger_joint", "right_outer_knuckle_joint"]
arm_base_link_prim_path = '/World/franka/panda_link0'
gripper_raw_open_close_range = [0, 1]
gripper_normalized_open_close_range = [0, 1]
gripper_signs = [1, 1]

[roborpc.sim_robots.isaac_sim.panda_3]
robot_arm_dof = 7
robot_gripper_dof = 2
action_dof = 15
robot_zero_action = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0, 0.0]
robot_description_path = 'panda_robot_descriptor.yaml'
rmpflow_config_path = 'panda_rmpflow_common.yaml'
urdf_path = 'franka_panda.urdf'
end_effector_frame_name = 'panda_link8'
gripper_base_link_prim_path = '/World/Robotiq_2F_85_edit_01/Robotiq_2F_85/base_link'
gripper_joint_prim_names = ["finger_joint", "right_outer_knuckle_joint"]
arm_base_link_prim_path = '/World/franka_01/panda_link0'
gripper_signs = [1, 1]

[roborpc.sim_robots.isaac_sim.panda_4]
robot_arm_dof = 7
robot_gripper_dof = 2
action_dof = 15
robot_zero_action = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0, 0.0]
robot_description_path = 'panda_robot_descriptor.yaml'
rmpflow_config_path = 'panda_rmpflow_common.yaml'
urdf_path = 'franka_panda.urdf'
end_effector_frame_name = 'panda_link8'
gripper_base_link_prim_path = '/World/Robotiq_2F_85_edit_02/Robotiq_2F_85/base_link'
gripper_joint_prim_names = ["finger_joint", "right_outer_knuckle_joint"]
arm_base_link_prim_path = '/World/franka_02/panda_link0'
gripper_signs = [1, 1]

[roborpc.sim_robots.isaac_sim.panda_5]
robot_arm_dof = 7
robot_gripper_dof = 2
action_dof = 15
robot_zero_action = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, 1.5707963267948966, 0.0, 0.0, 0.0]
robot_description_path = 'panda_robot_descriptor.yaml'
rmpflow_config_path = 'panda_rmpflow_common.yaml'
urdf_path = 'franka_panda.urdf'
end_effector_frame_name = 'panda_link8'
gripper_base_link_prim_path = '/World/Robotiq_2F_85_edit_03/Robotiq_2F_85/base_link'
gripper_joint_prim_names = ["finger_joint", "right_outer_knuckle_joint"]
arm_base_link_prim_path = '/World/franka_03/panda_link0'
gripper_signs = [1, 1]


[roborpc.sim_robots.isaac_sim.camera_1]
camera_prim_path = '/World/franka/panda_link8/handeye_camera'
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 60
resolution = [640, 480]

[roborpc.sim_robots.isaac_sim.camera_2]
camera_prim_path = '/World/franka/panda_link0/varied_1_camera'
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 60
resolution = [640, 480]

[roborpc.sim_robots.isaac_sim.camera_3]
camera_prim_path = '/World/franka/panda_link0/varied_2_camera'
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 60
resolution = [640, 480]

######### Mujoco Robot Configuration #########
[roborpc.sim_robots.mujoco]
robot_ids = [['panda_1']]
camera_ids = [['camera_1', 'camera_2', 'camera_3']]
server_ips_address = ['127.0.0.1']
sever_rpc_ports = ['4098']

[roborpc.sim_robots.mujoco.panda_1]
robot_arm_dof = 7
robot_gripper_dof = 1
robot_zero_action = [ -0.001229998898153242, -0.78373070703473, 0.00033452204524119444, -2.3621342130897784, -0.002939444554553038, 1.5585773693838316, 0.7862526640851296, 0.0]
#robot_zero_action = [0.00541805,  0.16084542,  0.02540027, -2.57049875,  0.01243444, 2.92530504,  0.80107014, 0.0]
gripper_raw_open_close_range = [0, 1]
gripper_normalized_open_close_range = [-1, 1]

[roborpc.sim_robots.mujoco.camera_1]
viewports = 'robot0_eye_in_hand'
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 20
resolution = [256, 256]

[roborpc.sim_robots.mujoco.camera_2]
viewports = 'robot0_robotview' # robot0_robotview for Lift and Insert, agentview for other tasks
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 20
resolution = [256, 256]

[roborpc.sim_robots.mujoco.camera_3]
viewports = 'frontview'
position = [0.0, 0.0, 0.0]
rotation = [0.0, 0.0, 0.0, 1.0]
frequency = 20
resolution = [256, 256]


