[roborpc.robot_env]
env_update_rate = 30

######### Robot Environment Configuration #########
# This section defines the environment configuration for the robots.
[roborpc.robots]
# ON or OFF
robot_ids = [['realman_1']]
server_ips_address = ['192.168.1.100']
sever_rpc_ports = ['']

[roborpc.robots.realman]
[roborpc.robots.realman.realman_1]
ip_address = '192.168.1.18'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.realman.realman_2]
ip_address = '192.168.1.19'
robot_arm_dof = 6
robot_gripper_dof = 1

[roborpc.robots.realman.realman_3]
ip_address = '192.168.1.20'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.realman.realman_4]
ip_address = '192.168.1.21'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.franka.panda_1]
ip_address = '192.168.1.20'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.franka.panda_2]
ip_address = '192.168.1.21'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.isaac_sim.isaac_sim_single_franka]
ip_address = '127.0.0.1'
robot_arm_dof = 7
robot_gripper_dof = 1

[roborpc.robots.dynamixel.dynamixel_controller_left_arm]
start_joints = [0.0, 0.0, 0.0, -1.5707963267948966, 0.0, -1.5707963267948966, 0.0, 0.0]
joint_ids = [0, 1, 2, 3, 4, 5, 6]
joint_signs = [1, -1, 1, -1, 1, 1, 1]
gripper = true
port = "/dev/serial/by-id/usb-1a86_USB_Single_Serial_5837053188-if00"
joint_offsets =  [3.141592653589793, 3.141592653589793, 6.283185307179586, 4.71238898038469, 6.283185307179586, 3.141592653589793, 3.141592653589793]
gripper_config = [7, 133, 175]
baudrate = 1000000

######### Camera Configuration #########
# This section defines the camera configuration for the robots.
[roborpc.cameras]
# ON or OFF
camera_ids = [['realsense_camera_1']]
server_ips_address = ['127.0.0.1']
server_rpc_ports = ['']

[roborpc.cameras.realsense_camera.realsense_camera_1]
camera_resolution = [640, 480]
camera_fps = 30
camera_serial_number = '231122070394'

[roborpc.cameras.realsense_camera.realsense_camera_2]
camera_resolution = [640, 480]
camera_fps = 30
camera_serial_number = '218622275485'

######### Controller Configuration #########
# This section defines the controller configuration for the robots.
[roborpc.controllers]
# ON or OFF
controller_ids = [['dynamixel_controller_left_arm']]
control_robot_ids = [['realman_1']]
server_ips_address = ['127.0.0.1']
sever_rpc_ports = ['']

######### Data Collector Configuration #########
# This section defines the data collector configuration for the robots.
[roborpc.collector.data_collector]
save_data_dir = "/media/jz08/SSD1/Log/droid/data/"
action_space = "joint_position"
gripper_action_space = "gripper_position"
use_one_side_camera = false # olny record left camera
use_hand_camera = true
use_left_camera = true
use_right_camera = true
use_rgb = true
use_depth = true
use_pointcloud = false
concatenate_images = false
image_width = 1280 #480
image_height = 720 #270
save_data_mode = "H5_FULL" # H5_SVO or H5_FULL or H5_MP4
save_data_speedup = false # for H5_SVO
use_zed_save_mp4 = false # for H5_MP4
save_audio = false
max_timesteps = 0 # 0 (not used) 1000
dt = 0.02 # act used
horizon = 50 # 0 for not used
use_align_color_depth = false
camera_fps = 15

######### Sim Robot Configuration #########
# This section defines the simulation robot configuration for the robots.
[roborpc.sim_robots]
daemon_host=''
daemon_port=6026

[roborpc.sim_robots.isaac_sim]
skip_rendering = false
task_host=''
task_port=6028
rpc_port=4245
env_usd_path = '/home/jz08/code_repo/franka_isaac/scenes/franka_06_17.usd'
robot_usd_path = '/home/jz08/code_repo/franka_isaac/scenes/default_environment.usd'

[roborpc.sim_robots.isaac_sim.single_franka_vision]
namespace_root = '/root'  # i.e., the robot Xform prefix
namespace = '/root/panda'  # i.e., the robot Xform prefix
init_position=[0, 0, 0]  # in unit cm
init_orientation=[0.0, 0.0, 0.0]  # in unit degree

[roborpc.sim_robots.isaac_sim.single_franka_vision.handeye_camera]
name = '/camera_handeye'
offset = [-0.11, 0.0, 0.0]
orientation = [180.0, 0.0, 0.0]
width = 640
height = 400
hori_aperture = 4.612866125858013
vert_aperture = 2.883041328661258
projection = 'perspective'
focal_length = 3.00312
focus_distance = 400


[roborpc.sim_robots.isaac_sim.single_franka_vision.varied_1_camera]
name = '/varied_1_camera'
offset = [-0.2, 0.9, 0.7]
orientation = [-120.0, 180.0, 56.0]
width = 640
height = 480
hori_aperture = 1.9215
vert_aperture = 1.44
projection = 'perspective'
focal_length = 1.25
focus_distance = 400

[roborpc.sim_robots.isaac_sim.single_franka_vision.varied_2_camera]
name = '/varied_2_camera'
offset = [-0.3, 0.5, 0.23]
orientation = [-81.0, 56.0, 152.0]
width = 640
height = 480
hori_aperture = 1.9215
vert_aperture = 1.44
projection = 'perspective'
focal_length = 1.25
focus_distance = 400


###### Kinematics Solver Configuration #########
[roborpc.kinematics_solver.curobo_solver_kinematic]
robot_cfg = 'rm75_6f.yml'
world_cfg = 'collision_table.yml'
robot_description = '/home/jz08/code_repo/roborpc/roborpc/robot_description/rm_description'

[roborpc.motion_planning.curobo_planner]
robot_cfg = 'rm75_6f.yml'
world_cfg = 'collision_table.yml'
robot_description = '/home/jz08/code_repo/roborpc/roborpc/robot_description/rm_description'

